# Woodpecker pipeline to build and publish container image to GHCR
when:
  event: [push, tag]
  branch: [main]

steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/cyberstorm-dev/golem
      context: .
      dockerfile: Dockerfile
      tags:
        - latest
        - "${CI_COMMIT_SHA:0:7}"
      platforms:
        - linux/amd64
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
